baseURL = "https://thirdgerb.github.io/"
languageCode = "zh-Hans"
title = "烈风's Blog"
theme = "AllinOne"
copyright = "&copy; 2016. All rights reserved."

# page
paginate = 10
hasCJKLanguage = true
newContentEditor = ""
summaryLength = 200


# google
googleAnalytics = "UA-81035041-1"

# disqus
disqusShortname = "thirdgerb"


[permalinks]

    blogs = "blogs/:year-:month/:slug/"

[params]
    brand = "烈风's Blog"
    avatar = "avatar.jpg"

    author = "烈风"
    description = ["一名离职写开源项目的程序猿", "吾有幽忧之疾, 而好无用之学", "方且为学，未暇治疾也"]

    #welcome
    welcome_head = "Hello, World!"
    welcome_word = "~ 开源社区代表先进生产关系 ~"

    # highlight
    highlightjs = true

    # blog
    latestpostscount         = 5
    bloggroupby              = 'month'

    #date
    dateform = "Jan 2, 2006"
    dateformful = "2006-06-06, 15:04"


    # slider
    slidesDirPath = "themes/AllinOne/static/img/header-slides"
    slidesDirPathURL = "img/header-slides"


    # links
    include_rss = true
    email = "thirdgerb@gmail.com"
    github = "https://github.com/thirdgerb"
    busuanzi = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[menu]

    [[menu.main]]
        name = "Posts"
        weight = 1
        identifier = "posts"
        url = "posts/"

    [[menu.main]]
        name = "About"
        weight = 9
        identifier = "about"
        url = "about/"
